apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-api
  namespace: nginx-ingress
spec:
  selector:
    matchLabels:
      app: test-api
  template:
    metadata:
      labels:
        app: test-api
    spec:
      containers:
      - name: test-api
        image: leminhduc201299/test-api:1.0.0.7
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
