--
-- Script was generated by Devart dbForge Studio for MySQL, Version 9.2.34.0
-- Product home page: http://www.devart.com/dbforge/mysql/studio
-- Script date 6/3/2023 10:23:18 AM
-- Server version: 8.0.20
-- Client version: 4.1
--

-- 
-- Disable foreign keys
-- 
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;

-- 
-- Set SQL mode
-- 
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;

-- 
-- Set character set the client will use to send SQL statements to the server
--
SET NAMES 'utf8';

DROP DATABASE IF EXISTS interview;

CREATE DATABASE IF NOT EXISTS interview
CHARACTER SET utf8mb4
COLLATE utf8mb4_0900_ai_ci;

--
-- Set default database
--
USE interview;

--
-- Create table `chitiet_nhapxuat`
--
CREATE TABLE IF NOT EXISTS chitiet_nhapxuat (
  so_phieu varchar(50) NOT NULL,
  ngay_lap_phieu date,
  ma_vt varchar(50) NOT NULL,
  ten_vt varchar(255),
  dvt varchar(255),
  sl_nhap float NOT NULL,
  sl_xuat float NOT NULL,
  created_date datetime,
  created_by varchar(255),
  modified_by varchar(255),
  modified_date datetime,
  PRIMARY KEY (so_phieu, ma_vt)
)
ENGINE = INNODB,
AVG_ROW_LENGTH = 2048,
CHARACTER SET utf8mb4,
COLLATE utf8mb4_0900_ai_ci;

--
-- Create index `IDX_chitiet_nhapxuat_ma_vt` on table `chitiet_nhapxuat`
--
ALTER TABLE chitiet_nhapxuat
ADD INDEX IDX_chitiet_nhapxuat_ma_vt (ma_vt);

--
-- Create index `IDX_chitiet_nhapxuat_ten_vt` on table `chitiet_nhapxuat`
--
ALTER TABLE chitiet_nhapxuat
ADD INDEX IDX_chitiet_nhapxuat_ten_vt (ten_vt);

DELIMITER $$

--
-- Create procedure `xoa_nhapkhau`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE xoa_nhapkhau (IN $so_phieu varchar(50), IN $ma_vt varchar(50))
BEGIN
  DELETE
    FROM chitiet_nhapxuat
  WHERE so_phieu = $so_phieu
    AND ma_vt = $ma_vt;
END
$$

--
-- Create procedure `timkiem_nhapkhau`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE timkiem_nhapkhau (IN $text_search varchar(255))
BEGIN
  IF $text_search IS NULL
    OR $text_search = '' THEN
    SELECT
      *
    FROM chitiet_nhapxuat
    ORDER BY created_date DESC;
  ELSE
    SELECT
      *
    FROM chitiet_nhapxuat cn
    WHERE cn.ma_vt LIKE CONCAT('%', $text_search, '%')
    OR cn.ten_vt LIKE CONCAT('%', $text_search, '%')
    ORDER BY created_date DESC;
  END IF;
END
$$

--
-- Create procedure `them_nhapkhau`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE them_nhapkhau (IN $so_phieu varchar(50), IN $ngay_lap_phieu date, IN $ma_vt varchar(50), IN $ten_vt varchar(255), IN $dvt varchar(255), IN $sl_nhap float, IN $sl_xuat float)
BEGIN
  INSERT chitiet_nhapxuat (so_phieu, ngay_lap_phieu, ma_vt, ten_vt, dvt, sl_nhap, sl_xuat)
    VALUES ($so_phieu, $ngay_lap_phieu, $ma_vt, $ten_vt, $dvt, $sl_nhap, $sl_xuat);
END
$$

--
-- Create procedure `ds_toncuoi_vt`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE ds_toncuoi_vt ()
BEGIN
  SELECT
    cn.ma_vt,
    MAX(cn.ten_vt),
    MAX(cn.dvt),
    (SUM(cn.sl_nhap) - SUM(cn.sl_xuat)) AS ton_cuoi
  FROM chitiet_nhapxuat cn
  GROUP BY cn.ma_vt
  HAVING SUM(cn.sl_nhap) - SUM(cn.sl_xuat) > 0;
END
$$

--
-- Create procedure `ct_nhapxuat_theongay`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE ct_nhapxuat_theongay (IN pngay_lap_phieu date)
BEGIN
  SELECT
    cn.so_phieu,
    cn.ngay_lap_phieu,
    cn.ma_vt,
    cn.ten_vt,
    cn.dvt,
    cn.sl_nhap,
    cn.sl_xuat
  FROM chitiet_nhapxuat cn
  WHERE CAST(cn.ngay_lap_phieu AS date) = CAST(pngay_lap_phieu AS date);
END
$$

--
-- Create procedure `checktrung_nhapkhau`
--
CREATE
DEFINER = 'root'@'localhost'
PROCEDURE checktrung_nhapkhau (IN $so_phieu varchar(50), IN $ma_vt varchar(50))
BEGIN
  SELECT
    *
  FROM chitiet_nhapxuat
  WHERE so_phieu = $so_phieu
  AND ma_vt = $ma_vt;
END
$$

DELIMITER ;

-- 
-- Dumping data for table chitiet_nhapxuat
--
INSERT INTO chitiet_nhapxuat VALUES
('PN-001', '2023-03-01', 'IP13', 'Iphone 13', 'Chiếc', 10, 0, '2023-06-02 22:43:07', NULL, NULL, '2023-06-02 22:42:56'),
('PN-001', '2023-03-01', 'IP14', 'Iphone 14', 'Chiếc', 20, 0, '2023-06-02 22:43:07', NULL, NULL, '2023-06-02 22:42:56'),
('PN-002', '2023-03-05', 'IP13', 'Iphone 13', 'Chiếc', 5, 0, '2023-06-02 22:43:07', NULL, NULL, '2023-06-02 22:42:56'),
('PN-002', '2023-03-05', 'IP14', 'Iphone 14', 'Chiếc', 10, 0, '2023-06-02 22:43:07', NULL, NULL, '2023-06-02 22:42:56'),
('PX-001', '2023-03-15', 'IP13', 'Iphone 13', 'Chiếc', 0, 5, '2023-06-02 22:43:07', NULL, NULL, '2023-06-02 22:42:56'),
('PX-001', '2023-03-15', 'IP14', 'Iphone 14', 'Chiếc', 0, 6, '2023-06-02 22:43:07', NULL, NULL, '2023-06-02 22:42:56'),
('PX-002', '2023-03-20', 'IP13', 'Iphone 13', 'Chiếc', 0, 10, '2023-06-02 22:43:07', NULL, NULL, '2023-06-02 22:42:56'),
('PX-002', '2023-03-20', 'IP14', 'Iphone 14', 'Chiếc', 0, 8, '2023-06-02 22:43:07', NULL, NULL, '2023-06-02 22:42:56');

-- 
-- Restore previous SQL mode
-- 
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;

-- 
-- Enable foreign keys
-- 
/*!40014 SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS */;