apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: lmduc-nginx-ingress
  # annotations:
  #   ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: nginx.org/ingress-controller
