apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: http-test-svc
  name: http-test-svc
  namespace: nginx-ingress
spec:
  replicas: 2
  selector:
    matchLabels:
      run: http-test-app
  template:
    metadata:
      labels:
        run: http-test-app
    spec:
      containers:
      - image: httpd
        imagePullPolicy: IfNotPresent
        name: http
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nodeport-svc
  namespace: nginx-ingress
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    nodePort: 31005
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
    nodePort: 31006
  selector:
    run: http-test-app
---
apiVersion: v1
kind: Service
metadata:
  name: balancer-svc
  namespace: nginx-ingress
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    nodePort: 31005
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
    nodePort: 31006
  selector:
    run: http-test-app
