apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    nodePort: 31008
  - port: 443
    targetPort: 443
    protocol: TCP
    name: https
    nodePort: 31009
  selector:
    app: nginx-ingress
